{{ $kccVersion := "0.5.0" -}}
[".bin/kcc-cache"]
    type = "file"
    url = "https://github.com/ryodocx/kube-credential-cache/releases/download/v{{ $kccVersion }}/kube-credential-cache_{{ $kccVersion }}_Linux_x86_64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".bin/kcc-cache".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "kcc-cache"]
