#!/bin/bash -e

display_usage() {
    echo "This script will install a public key from 1password to a remote host."
    echo -e "\nUsage: $0 target_host [username] [client_hostname]\n"
}

if [  $# -lt 1 ]; then
    display_usage
    exit 1
fi

if [[ ( $@ == "--help") ||  $@ == "-h" ]]; then
    display_usage
    exit 0
fi

target_host=$1
user=${2:-gunzy}
client_hostname=${3:-CURRENT}

echo "Creating temp directory..."
tmp_dir=$(mktemp -d)
echo "Done!"

if [ "${client_hostname}" == 'CURRENT' ]; then
    keyname="${user}-${HOSTNAME}"
elif [ "${client_hostname}" == '' ]; then
    keyname="${user}"
else
    keyname="${user}-${client_hostname}"
fi
key_temp_file="${tmp_dir}/${keyname}.pub"

echo "Get public key from 1password, you may be prompted to unlock the vault..."
op read --account my.1password.com "op://Private/${keyname}/public_key" > $key_temp_file
echo "Done!"

echo "Copying the public key to the remote host..."
ssh-copy-id -f -i $key_temp_file $user@$target_host
echo "Done!"

echo "Removing temporary key..."
rm -f $key_temp_file

echo "Done!"
