#!/bin/bash -e
# set expirationTimestamp to ensure that clients will reauth on a regular basis and will throw away cached credentials
echo "$(cat << EOF
{
    "kind": "ExecCredential",
    "apiVersion": "client.authentication.k8s.io/v1beta1",
    "spec": {},
    "status":
    {
        "expirationTimestamp": "$(date --utc +%FT%TZ -d '+1 hour')",
        "clientCertificateData": $(op read "op://${VAULT}/${ITEM}/user/client-certificate-data" | base64 -d | jq -R -s '.'),
        "clientKeyData": $(op read "op://${VAULT}/${ITEM}/user/client-key-data" | base64 -d | jq -R -s '.')
    }
}
EOF
)" | jq -cr
