#!/bin/bash -e
# set expirationTimestamp to ensure that clients will reauth on a regular basis and will throw away cached credentials
creds=$(op item get --cache \
  --fields "label=user.client-certificate-data,label=user.client-key-data" \
  --format 'json' \
  --vault "${VAULT}" \
  "${ITEM}")

ccd=$(echo "$creds" | jq -r '.[0].value' | base64 -d | jq -R -s '.')
ckd=$(echo "$creds" | jq -r '.[1].value' | base64 -d | jq -R -s '.')

echo "$(cat << EOF
{
    "kind": "ExecCredential",
    "apiVersion": "client.authentication.k8s.io/v1beta1",
    "spec": {},
    "status":
    {
        "expirationTimestamp": "$(date --utc +%FT%TZ -d '+1 hour')",
        "clientCertificateData": $ccd,
        "clientKeyData": $ckd
    }
}
EOF
)" | jq -cr
