set term=xterm-256color
syntax on

set nocompatible

set ignorecase
set smartcase
set number
set incsearch
set hlsearch
set linebreak
set autoindent
set smartindent
set showtabline=1
set nobackup

set wildmode=longest,list
set wildmenu

set showcmd
set autowrite
set hidden

set history=1000
set scrolloff=5
set ruler
set backspace=indent,eol,start
set shortmess=atI
set autochdir
set viminfo='20,<50,s10,h,%
let mapleader = ","
set background=dark
colorscheme base16-monokai

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'ConradIrwin/vim-bracketed-paste'

call vundle#end()
filetype plugin indent on

let g:airline_powerline_fonts = 1
set laststatus=2
let g:airline_theme='dark'

