#!/bin/bash -e

OP_ACCOUNT="$1"
OP_VAULT="$2"
OP_ITEM="$3"

op item get --account "${OP_ACCOUNT}" --cache --fields "label=aws_access_key_id,label=aws_secret_access_key" --format 'json' --vault "${OP_VAULT}" "${OP_ITEM}" | jq '
  {
    Version: 1,
    AccessKeyId: .[0].value,
    SecretAccessKey: .[1].value
  }'
